//! Grammar-specific IDs mapped to the node categories used by call resolution.
//! Keep this boundary explicit: the same numeric ID means different things in each grammar.
use crate::{Cpp, Java, Javascript, LANG, Node, Python, Rust, Tsx, Typescript};

#[derive(Clone, Copy, PartialEq, Eq)]
pub(super) enum Kind {
    ArrowFunction,
    Assignment,
    AssignmentExpression,
    Attribute,
    AugmentedAssignment,
    AugmentedAssignmentExpression,
    Block,
    BlockComment,
    Call,
    CallExpression,
    CatchClause,
    ClassBody,
    ClassDeclaration,
    ClassDefinition,
    ClassSpecifier,
    ClosureExpression,
    CompoundStatement,
    ConstItem,
    ConstructorDeclaration,
    Declaration,
    DeclarationList,
    DecoratedDefinition,
    DeleteStatement,
    DictionaryComprehension,
    EnhancedForStatement,
    EnumItem,
    ExceptClause,
    Final,
    ForExpression,
    ForInStatement,
    ForRangeLoop,
    ForStatement,
    FunctionDeclaration,
    FunctionDefinition,
    FunctionExpression,
    FunctionItem,
    GeneratorExpression,
    GeneratorFunction,
    GeneratorFunctionDeclaration,
    GlobalStatement,
    Identifier,
    IfExpression,
    ImplItem,
    ImportFromStatement,
    ImportStatement,
    InitDeclarator,
    Lambda,
    LambdaExpression,
    LetCondition,
    LetDeclaration,
    LineComment,
    ListComprehension,
    MacroDefinition,
    MacroInvocation,
    MatchArm,
    MatchStatement,
    MemberExpression,
    MethodDeclaration,
    MethodDefinition,
    MethodInvocation,
    ModItem,
    Modifiers,
    NamespaceDefinition,
    NonlocalStatement,
    OptionalParameterDeclaration,
    PairPattern,
    ParameterDeclaration,
    PreprocDef,
    PreprocFunctionDef,
    Private,
    SetComprehension,
    ShorthandPropertyIdentifierPattern,
    SpreadParameter,
    StatementBlock,
    Static,
    StaticItem,
    StructItem,
    StructSpecifier,
    Subscript,
    SubscriptExpression,
    TraitItem,
    TypeAnnotation,
    TypeIdentifier,
    UnionSpecifier,
    UseDeclaration,
    UsingDeclaration,
    VariableDeclaration,
    VariableDeclarator,
    WhileExpression,
    WithStatement,
    Other,
}

pub(super) fn kind(node: Node, language: LANG) -> Kind {
    match language {
        LANG::Cpp => match Cpp::from(node.kind_id()) {
            Cpp::AssignmentExpression | Cpp::AssignmentExpression2 => Kind::AssignmentExpression,
            Cpp::Attribute => Kind::Attribute,
            Cpp::CallExpression | Cpp::CallExpression2 => Kind::CallExpression,
            Cpp::CatchClause => Kind::CatchClause,
            Cpp::ClassSpecifier => Kind::ClassSpecifier,
            Cpp::CompoundStatement => Kind::CompoundStatement,
            Cpp::Declaration | Cpp::Declaration2 | Cpp::Declaration3 | Cpp::Declaration4 => {
                Kind::Declaration
            }
            Cpp::DeclarationList => Kind::DeclarationList,
            Cpp::Final => Kind::Final,
            Cpp::ForRangeLoop => Kind::ForRangeLoop,
            Cpp::ForStatement => Kind::ForStatement,
            Cpp::FunctionDefinition
            | Cpp::FunctionDefinition2
            | Cpp::FunctionDefinition3
            | Cpp::FunctionDefinition4 => Kind::FunctionDefinition,
            Cpp::Identifier => Kind::Identifier,
            Cpp::InitDeclarator => Kind::InitDeclarator,
            Cpp::LambdaExpression => Kind::LambdaExpression,
            Cpp::NamespaceDefinition => Kind::NamespaceDefinition,
            Cpp::OptionalParameterDeclaration => Kind::OptionalParameterDeclaration,
            Cpp::ParameterDeclaration => Kind::ParameterDeclaration,
            Cpp::PreprocDef => Kind::PreprocDef,
            Cpp::PreprocFunctionDef => Kind::PreprocFunctionDef,
            Cpp::Private => Kind::Private,
            Cpp::Static => Kind::Static,
            Cpp::StructSpecifier => Kind::StructSpecifier,
            Cpp::SubscriptExpression => Kind::SubscriptExpression,
            Cpp::TypeIdentifier => Kind::TypeIdentifier,
            Cpp::UnionSpecifier => Kind::UnionSpecifier,
            Cpp::UsingDeclaration => Kind::UsingDeclaration,
            _ => Kind::Other,
        },
        LANG::Rust => match Rust::from(node.kind_id()) {
            Rust::AssignmentExpression => Kind::AssignmentExpression,
            Rust::Attribute => Kind::Attribute,
            Rust::Block2 | Rust::Block => Kind::Block,
            Rust::BlockComment => Kind::BlockComment,
            Rust::CallExpression => Kind::CallExpression,
            Rust::ClosureExpression => Kind::ClosureExpression,
            Rust::ConstItem => Kind::ConstItem,
            Rust::DeclarationList => Kind::DeclarationList,
            Rust::EnumItem => Kind::EnumItem,
            Rust::ForExpression => Kind::ForExpression,
            Rust::FunctionItem => Kind::FunctionItem,
            Rust::Identifier => Kind::Identifier,
            Rust::IfExpression => Kind::IfExpression,
            Rust::ImplItem => Kind::ImplItem,
            Rust::LetCondition => Kind::LetCondition,
            Rust::LetDeclaration => Kind::LetDeclaration,
            Rust::LineComment => Kind::LineComment,
            Rust::MacroDefinition => Kind::MacroDefinition,
            Rust::MacroInvocation => Kind::MacroInvocation,
            Rust::MatchArm | Rust::MatchArm2 => Kind::MatchArm,
            Rust::ModItem => Kind::ModItem,
            Rust::Static => Kind::Static,
            Rust::StaticItem => Kind::StaticItem,
            Rust::StructItem => Kind::StructItem,
            Rust::TraitItem => Kind::TraitItem,
            Rust::TypeIdentifier => Kind::TypeIdentifier,
            Rust::UseDeclaration => Kind::UseDeclaration,
            Rust::WhileExpression => Kind::WhileExpression,
            _ => Kind::Other,
        },
        LANG::Python => match Python::from(node.kind_id()) {
            Python::Assignment => Kind::Assignment,
            Python::Attribute => Kind::Attribute,
            Python::AugmentedAssignment => Kind::AugmentedAssignment,
            Python::Block | Python::Block2 => Kind::Block,
            Python::Call => Kind::Call,
            Python::ClassDefinition => Kind::ClassDefinition,
            Python::DecoratedDefinition => Kind::DecoratedDefinition,
            Python::DeleteStatement => Kind::DeleteStatement,
            Python::DictionaryComprehension => Kind::DictionaryComprehension,
            Python::ExceptClause => Kind::ExceptClause,
            Python::ForStatement => Kind::ForStatement,
            Python::FunctionDefinition => Kind::FunctionDefinition,
            Python::GeneratorExpression => Kind::GeneratorExpression,
            Python::GlobalStatement => Kind::GlobalStatement,
            Python::Identifier => Kind::Identifier,
            Python::ImportFromStatement => Kind::ImportFromStatement,
            Python::ImportStatement => Kind::ImportStatement,
            Python::Lambda3 | Python::Lambda | Python::Lambda2 => Kind::Lambda,
            Python::ListComprehension => Kind::ListComprehension,
            Python::MatchStatement => Kind::MatchStatement,
            Python::NonlocalStatement => Kind::NonlocalStatement,
            Python::SetComprehension => Kind::SetComprehension,
            Python::Subscript => Kind::Subscript,
            Python::WithStatement => Kind::WithStatement,
            _ => Kind::Other,
        },
        LANG::Java => match Java::from(node.kind_id()) {
            Java::AssignmentExpression => Kind::AssignmentExpression,
            Java::Block => Kind::Block,
            Java::BlockComment => Kind::BlockComment,
            Java::CatchClause => Kind::CatchClause,
            Java::ClassBody => Kind::ClassBody,
            Java::ClassDeclaration => Kind::ClassDeclaration,
            Java::ConstructorDeclaration => Kind::ConstructorDeclaration,
            Java::Declaration => Kind::Declaration,
            Java::EnhancedForStatement => Kind::EnhancedForStatement,
            Java::Final => Kind::Final,
            Java::ForStatement => Kind::ForStatement,
            Java::Identifier => Kind::Identifier,
            Java::LambdaExpression => Kind::LambdaExpression,
            Java::LineComment => Kind::LineComment,
            Java::MethodDeclaration => Kind::MethodDeclaration,
            Java::MethodInvocation => Kind::MethodInvocation,
            Java::Modifiers => Kind::Modifiers,
            Java::Private => Kind::Private,
            Java::SpreadParameter => Kind::SpreadParameter,
            Java::Static => Kind::Static,
            Java::TypeIdentifier => Kind::TypeIdentifier,
            Java::VariableDeclarator => Kind::VariableDeclarator,
            _ => Kind::Other,
        },
        LANG::Javascript => match Javascript::from(node.kind_id()) {
            Javascript::ArrowFunction => Kind::ArrowFunction,
            Javascript::AssignmentExpression => Kind::AssignmentExpression,
            Javascript::AugmentedAssignmentExpression => Kind::AugmentedAssignmentExpression,
            Javascript::CallExpression | Javascript::CallExpression2 => Kind::CallExpression,
            Javascript::CatchClause => Kind::CatchClause,
            Javascript::ClassBody => Kind::ClassBody,
            Javascript::ClassDeclaration => Kind::ClassDeclaration,
            Javascript::Declaration => Kind::Declaration,
            Javascript::ForInStatement => Kind::ForInStatement,
            Javascript::ForStatement => Kind::ForStatement,
            Javascript::FunctionDeclaration => Kind::FunctionDeclaration,
            Javascript::FunctionExpression => Kind::FunctionExpression,
            Javascript::GeneratorFunction => Kind::GeneratorFunction,
            Javascript::GeneratorFunctionDeclaration => Kind::GeneratorFunctionDeclaration,
            Javascript::Identifier | Javascript::Identifier2 => Kind::Identifier,
            Javascript::ImportStatement => Kind::ImportStatement,
            Javascript::MemberExpression
            | Javascript::MemberExpression2
            | Javascript::MemberExpression3 => Kind::MemberExpression,
            Javascript::MethodDefinition => Kind::MethodDefinition,
            Javascript::PairPattern => Kind::PairPattern,
            Javascript::ShorthandPropertyIdentifierPattern => {
                Kind::ShorthandPropertyIdentifierPattern
            }
            Javascript::StatementBlock => Kind::StatementBlock,
            Javascript::Static => Kind::Static,
            Javascript::SubscriptExpression => Kind::SubscriptExpression,
            Javascript::UsingDeclaration => Kind::UsingDeclaration,
            Javascript::VariableDeclaration => Kind::VariableDeclaration,
            Javascript::VariableDeclarator => Kind::VariableDeclarator,
            Javascript::WithStatement => Kind::WithStatement,
            _ => Kind::Other,
        },
        LANG::Typescript => match Typescript::from(node.kind_id()) {
            Typescript::ArrowFunction => Kind::ArrowFunction,
            Typescript::AssignmentExpression => Kind::AssignmentExpression,
            Typescript::AugmentedAssignmentExpression => Kind::AugmentedAssignmentExpression,
            Typescript::CallExpression
            | Typescript::CallExpression2
            | Typescript::CallExpression3
            | Typescript::CallExpression4 => Kind::CallExpression,
            Typescript::CatchClause => Kind::CatchClause,
            Typescript::ClassBody => Kind::ClassBody,
            Typescript::ClassDeclaration => Kind::ClassDeclaration,
            Typescript::Declaration => Kind::Declaration,
            Typescript::ForInStatement => Kind::ForInStatement,
            Typescript::ForStatement => Kind::ForStatement,
            Typescript::FunctionDeclaration => Kind::FunctionDeclaration,
            Typescript::FunctionExpression => Kind::FunctionExpression,
            Typescript::GeneratorFunction => Kind::GeneratorFunction,
            Typescript::GeneratorFunctionDeclaration => Kind::GeneratorFunctionDeclaration,
            Typescript::Identifier => Kind::Identifier,
            Typescript::ImportStatement => Kind::ImportStatement,
            Typescript::MemberExpression
            | Typescript::MemberExpression2
            | Typescript::MemberExpression3
            | Typescript::MemberExpression4 => Kind::MemberExpression,
            Typescript::MethodDefinition => Kind::MethodDefinition,
            Typescript::PairPattern => Kind::PairPattern,
            Typescript::Private => Kind::Private,
            Typescript::ShorthandPropertyIdentifierPattern => {
                Kind::ShorthandPropertyIdentifierPattern
            }
            Typescript::StatementBlock => Kind::StatementBlock,
            Typescript::Static => Kind::Static,
            Typescript::SubscriptExpression | Typescript::SubscriptExpression2 => {
                Kind::SubscriptExpression
            }
            Typescript::TypeAnnotation => Kind::TypeAnnotation,
            Typescript::TypeIdentifier => Kind::TypeIdentifier,
            Typescript::VariableDeclaration => Kind::VariableDeclaration,
            Typescript::VariableDeclarator => Kind::VariableDeclarator,
            Typescript::WithStatement => Kind::WithStatement,
            _ => Kind::Other,
        },
        LANG::Tsx => match Tsx::from(node.kind_id()) {
            Tsx::ArrowFunction => Kind::ArrowFunction,
            Tsx::AssignmentExpression => Kind::AssignmentExpression,
            Tsx::AugmentedAssignmentExpression => Kind::AugmentedAssignmentExpression,
            Tsx::CallExpression
            | Tsx::CallExpression2
            | Tsx::CallExpression3
            | Tsx::CallExpression4 => Kind::CallExpression,
            Tsx::CatchClause => Kind::CatchClause,
            Tsx::ClassBody => Kind::ClassBody,
            Tsx::ClassDeclaration => Kind::ClassDeclaration,
            Tsx::Declaration => Kind::Declaration,
            Tsx::ForInStatement => Kind::ForInStatement,
            Tsx::ForStatement => Kind::ForStatement,
            Tsx::FunctionDeclaration => Kind::FunctionDeclaration,
            Tsx::FunctionExpression => Kind::FunctionExpression,
            Tsx::GeneratorFunction => Kind::GeneratorFunction,
            Tsx::GeneratorFunctionDeclaration => Kind::GeneratorFunctionDeclaration,
            Tsx::Identifier | Tsx::Identifier2 => Kind::Identifier,
            Tsx::ImportStatement => Kind::ImportStatement,
            Tsx::MemberExpression
            | Tsx::MemberExpression2
            | Tsx::MemberExpression3
            | Tsx::MemberExpression4 => Kind::MemberExpression,
            Tsx::MethodDefinition => Kind::MethodDefinition,
            Tsx::PairPattern => Kind::PairPattern,
            Tsx::Private => Kind::Private,
            Tsx::ShorthandPropertyIdentifierPattern => Kind::ShorthandPropertyIdentifierPattern,
            Tsx::StatementBlock => Kind::StatementBlock,
            Tsx::Static => Kind::Static,
            Tsx::SubscriptExpression | Tsx::SubscriptExpression2 => Kind::SubscriptExpression,
            Tsx::TypeAnnotation => Kind::TypeAnnotation,
            Tsx::TypeIdentifier => Kind::TypeIdentifier,
            Tsx::VariableDeclaration => Kind::VariableDeclaration,
            Tsx::VariableDeclarator => Kind::VariableDeclarator,
            Tsx::WithStatement => Kind::WithStatement,
            _ => Kind::Other,
        },
    }
}
